feat!: remove inspect symbol from public interface
The inspect symbol being part of the public interfaces causes type incompatibilities between otherwise compatible versions of this library.
Typescript treats the symbol as unique, even though the same symbol will be used across versions.

Eg:
Library A uses @multiformats/multiaddr@1.1.8
Library B uses A and @multiformats/multiaddr@1.2.0

The types will not match and there will be a type error:
```
error TS2741: Property '[inspect]' is missing in type 'import("/path/to/B/node_modules/@multiformats/multiaddr/dist/src/index").Multiaddr' but required in type 'import("/path/to/B/node_modules/A/node_modules/@multiformats/multiaddr/dist/src/index").Multiaddr'.
```